Add overloaded RuntimeBoxUnboxPropogator.toBinaryString$$PHOSPHORTAGGED(II)Ljava/lang/String
There is an overloaded method that takes and int and long; not an
overloaded method that takes int and int. This caused
NoSuchMethodErrors to be thrown when using the runtime api, e.g., when dumping
taints.